name: Deploy Serverless Stack

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write # for OIDC

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Show what sub will be
        run: echo "sub = repo:${{ github.repository }}:${{ github.ref }}"

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}
          role-session-name: gha-cdk-${{ github.run_id }}

      - name: Verify AWS identity
        run: aws sts get-caller-identity

      
